// <auto-generated />
using System;
using Corrente.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Corrente.Migrations
{
    [DbContext(typeof(CorrenteContext))]
    [Migration("20210328202858_TipoInstituicaoForeignKey")]
    partial class TipoInstituicaoForeignKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Corrente.Models.Doacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DtCriada");

                    b.Property<DateTime>("DtRealizada");

                    b.Property<int?>("InstituicaoId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("InstituicaoId");

                    b.ToTable("Doacao");
                });

            modelBuilder.Entity("Corrente.Models.Instituicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<DateTime>("DtCadastro");

                    b.Property<string>("Nome");

                    b.Property<double>("Pontuacao");

                    b.Property<string>("Telefone");

                    b.Property<int>("TipoInstituicaoId");

                    b.HasKey("Id");

                    b.HasIndex("TipoInstituicaoId");

                    b.ToTable("Instituicao");
                });

            modelBuilder.Entity("Corrente.Models.TipoInstituicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("TipoInstituicao");
                });

            modelBuilder.Entity("Corrente.Models.Doacao", b =>
                {
                    b.HasOne("Corrente.Models.Instituicao", "Instituicao")
                        .WithMany("Doacoes")
                        .HasForeignKey("InstituicaoId");
                });

            modelBuilder.Entity("Corrente.Models.Instituicao", b =>
                {
                    b.HasOne("Corrente.Models.TipoInstituicao", "TipoInstituicao")
                        .WithMany("Instituicoes")
                        .HasForeignKey("TipoInstituicaoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
